/*
 * ============================================================================
 *
 *  PawnUnit
 *
 *  File:          pawnunit.inc
 *  Type:          Include
 *  Description:   PawnUnit testing API.
 *  Notes:         Include this file to include the whole PawnUnit API. 
 *
 *  Copyright (C) 2012  Richard Helgeby
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * ============================================================================
 */

#if defined _pawnunit_included
 #endinput
#endif
#define _pawnunit_included

//#include <pawnunit/assert>
#include <pawnunit/main>
#include <pawnunit/testcase>
#include <pawnunit/testcollection>
